component_depth: 4
languages:
- name: cpp
  production:
    include:
      - /src/include/ikarus/.*\.cpp
      - /src/include/ikarus/.*\.h
    exclude:
      - /tests/.*\.cpp
  test:
    include:
      - /tests/.*\.cpp
