# Project information
site_name: ikarus
site_description: ikarus documentation.
site_author: Alexander Müller
site_url: https://IkarusRepo.github.io

# Repository
repo_name: IkarusRepo/Ikarus
repo_url: https://github.com/IkarusRepo/Ikarus

# Copyright
copyright: 'Copyright &copy; 2021 Alexander Müller'

# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - content.code.annotate
  palette:
    - scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode



# Path where the markdown files are
docs_dir: 'website'

# Navigation
nav:
  - Home: index.md
  - Download: download.md
  - Documentation:
    - How to edit the documentation: documentation/howToEdit.md
    - Build the documentation locally: documentation/BuildTheDocumentationLocally.md
  - Tutorials:
    - Overview: tutorials/tutorialsOverview.md
    - Grid    : tutorials/tutGrid.md
  - Theory and Implementation:
    - Overview: theory/theoryOverview.md
    - Geometry: theory/theoryGeometry.md
    - Grid: theory/theoryGrid.md
    - Finite Elements: theory/theoryFiniteElement.md
  - Examples:
      - Integrate pi: examples/integrate_pi.md


# Customization
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - drawio-exporter:
      drawio_args:
        - --no-sandbox
  - macros:
      module_name: mkdocs-macros
