name: check-Eigen-Version
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Work Dir
        run: mkdir build
      - name: DownloadDependencies
        uses: actions/checkout@master
        with:
          repository: rath3t/IkarusDependencies
          path: ./Dependencies
      - name: BuildDependencies 
        working-directory: ./Dependencies
        run: .\installIkarusDependencies.sh  
