name: Build Docker Images

on:
  push:
    branches:
      - 'main'
    paths:
      - 'scripts/ci_docker/debian/DockerFile'
      - '.github/workflows/build_docker_image_debian.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'scripts/ci_docker/debian/DockerFile'
      - '.github/workflows/build_docker_image_debian.yml'

jobs:
  build-docker-debian:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file scripts/ci_docker/debian/DockerFile --tag rath3t/ci-debian-bookworm
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish the Docker image
        if: ${{ github.event_name == 'push'}}
        run: docker push rath3t/ci-debian-bookworm