name: Build Docker Images for CI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'scripts/ci_docker/docker_file_ci_ubuntu_20_04/ubuntu'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'scripts/ci_docker/docker_file_ci_ubuntu_20_04/ubuntu'

jobs:
  build-docker-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file scripts/ci_docker/ubuntu/DockerFile --tag rath3t/ci-ubuntu-21-04
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish the Docker image
        if: ${{ github.event_name == 'push'}}
        # only push the new image when the changes are merged to master
        run: docker push rath3t/ci-ubuntu-21-04