name: check-Eigen-Version
on: [push]
jobs:
  check-Eigen-Version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Work Dir
        run: mkdir build
      - name: Install Winlibs
        run: |
          mkdir winlibs
          Invoke-WebRequest -Uri https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-12.0.0-9.0.0-r2/winlibs-x86_64-posix-seh-gcc-11.1.0-llvm-12.0.0-mingw-w64-9.0.0-r2.7z -OutFile ./winlibs/libs.7z
          cd winlibs
          7z x libs.7z
          ls
  
      - name: DownloadDependencies
        run: |
          mkdir winlibs
          Invoke-WebRequest -Uri https://github.com/rath3t/IkarusDependencies/blob/master/Dependencies_release.7z -w64-9.0.0-r2.7z -OutFile /dependencies.7z
          7z x dependencies.7z
          ls
   #   - name: BuildDependencies 
   #     working-directory: ./Dependencies
   #     run: .\installIkarusDependencies.ps1
      - name: Build dependencies 
        working-directory: ./Dependencies
        run: |
          mkdir cmake-build-release
          cd cmake-build-release
          ls
          cmake ../  -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_C_COMPILER="D:/a/Ikarus/Ikarus/winlibs/mingw64/bin/gcc.exe" -DCMAKE_CXX_COMPILER="D:/a/Ikarus/Ikarus/winlibs/mingw64/bin/g++.exe"
          cmake --build . --parallel 9
