# SPDX-FileCopyrightText: 2022 The Ikarus Developers mueller@ibb.uni-stuttgart.de
# SPDX-License-Identifier: CC0-1.0

name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download, tag, push and save docker images for new release
        run: |
          docker pull rath3t/ikarus-dev:latest
          docker tag rath3t/ikarus-dev:latest rath3t/ikarus-dev:${{ github.ref_name }}
          docker push rath3t/ikarus-dev:${{ github.ref_name }}
          docker pull rath3t/ikarus:latest
          docker tag rath3t/ikarus:latest rath3t/ikarus:${{ github.ref_name }}
          docker push rath3t/ikarus:${{ github.ref_name }}
          docker save rath3t/ikarus-dev:${{ github.ref_name }} | gzip -9 > ikarus-dev-docker-${{ github.ref_name }}.tar.gz
          docker save rath3t/ikarus-dev:${{ github.ref_name }} | zip  -9 > ikarus-dev-docker-${{ github.ref_name }}.zip
          docker save rath3t/ikarus:${{ github.ref_name }}     | gzip -9 > ikarus-docker-${{ github.ref_name }}.tar.gz
          docker save rath3t/ikarus:${{ github.ref_name }}     | zip  -9 > ikarus-docker-${{ github.ref_name }}.zip
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-dev-docker-${{ github.ref_name }}.tar.gz -F 'jsonData={"description":"The docker container to develop with Ikarus",     "categories":["Docker image"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-dev-docker-${{ github.ref_name }}.zip    -F 'jsonData={"description":"The docker container to develop with Ikarus",     "categories":["Docker image"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-docker-${{ github.ref_name }}.tar.gz     -F 'jsonData={"description":"The docker container to run examples with Ikarus","categories":["Docker image"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-docker-${{ github.ref_name }}.zip        -F 'jsonData={"description":"The docker container to run examples with Ikarus","categories":["Docker image"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"

      - name: Zip and upload current Ikarus to DARUS
        run: |
          tar -czf ikarus-sources-${{ github.ref_name }}.tar.gz ./repo
          zip -9r  ikarus-sources-${{ github.ref_name }}.zip    ./repo
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-sources-${{ github.ref_name }}.tar.gz -F 'jsonData={"description":"Ikarus sources":"categories":["Code"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-sources-${{ github.ref_name }}.zip    -F 'jsonData={"description":"Ikarus sources":"categories":["Code"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"

      - name: Checkout ikarus-examples and create tag, push it, zip it and add it to DARUS
        run: | 
          git clone https://github.com/ikarus-project/ikarus-examples.git
          cd ikarus-examples
          git tag ${{ github.ref_name }}
          git push https://${{ secrets.ORGANIZATION_TOKEN }}@github.com/ikarus-project/ikarus-examples.git ${{ github.ref_name }}
          cd ..
          tar -czf ikarus-examples-${{ github.ref_name }}.tar.gz ./ikarus-examples 
          zip -9r  ikarus-examples-${{ github.ref_name }}.zip    ./ikarus-examples 
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-examples-${{ github.ref_name }}.tar.gz -F 'jsonData={"description":"Ikarus examples":"categories":["Code"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-examples-${{ github.ref_name }}.zip    -F 'jsonData={"description":"Ikarus examples":"categories":["Code"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref_name }}
          draft: true
          prerelease: true
          title: ${{ github.ref_name }}
          files: |
            ikarus-dev-docker-${{ github.ref_name }}.tar.gz
            ikarus-dev-docker-${{ github.ref_name }}.zip
            ikarus-docker-${{ github.ref_name }}.tar.gz
            ikarus-docker-${{ github.ref_name }}.zip
            ikarus-examples-${{ github.ref_name }}.tar.gz
            ikarus-examples-${{ github.ref_name }}.zip
