# SPDX-FileCopyrightText: 2022 The Ikarus Developers mueller@ibb.uni-stuttgart.de
# SPDX-License-Identifier: CC0-1.0

name: Create release

on:
  push:
    tags:
      - "v*"

env:
  MKDOCSOFFLINE: true

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'repo'
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup Mkdocs
        run: |
          pip install mkdocs
          pip install git+https://${{ secrets.MKDOCS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mkdocs-macros-plugin
          pip install mkdocs-drawio-exporter
          pip install mkdocs-bibtex
          pip install mike
          pip install mkdocs-glightbox
          pip install pillow cairosvg
          sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev  

      - name: Build Website
        run: |
          git clone https://github.com/ikarus-project/ikarus-project.github.io.git
          cd ikarus-project.github.io
          git fetch origin gh-pages --depth=1
          cp -R ../repo/docs/ .
          cp -R ../repo/src/ .
          git config --local user.email "${{ github.event.head_commit.author.email }}"
          git config --local user.name "${{ github.event.head_commit.author.name }}"
          cd docs
          export MKDOCSOFFLINE=false
          mike deploy ${{ github.ref_name }}  --config-file mkdocs.insiders.yml
          git remote set-url origin https://${{ secrets.ORGANIZATION_TOKEN }}@github.com/ikarus-project/ikarus-project.github.io.git
          git commit --amend -m "Deploy ${{ github.ref_name }} at ${{ github.event.head_commit.message }} ikarus-project/ikarus@${{ github.event.head_commit.id }}" --allow-empty
          git push origin gh-pages 
          export MKDOCSOFFLINE=true

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Build Website for offline use
        run: |
          cd ./repo/docs
          cmake -B .build
          cmake --build .build --target site
          mv site documentation-${{ github.ref_name }}
          tar -czf docs-${{ github.ref_name }}.tar.gz ./documentation-${{ github.ref_name }}
          zip -9r  docs-${{ github.ref_name }}.zip    ./documentation-${{ github.ref_name }}
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@docs-${{ github.ref_name }}.tar.gz -F 'jsonData={"description":"Ikarus examples","categories":["Documentation"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@docs-${{ github.ref_name }}.zip    -F 'jsonData={"description":"Ikarus examples","categories":["Documentation"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"          

      - name: Download, tag, push and save docker images for new release
        run: |
          docker pull rath3t/ikarus-dev:latest
          docker tag rath3t/ikarus-dev:latest rath3t/ikarus-dev:${{ github.ref_name }}
          docker push rath3t/ikarus-dev:${{ github.ref_name }}
          docker pull rath3t/ikarus:latest
          docker tag rath3t/ikarus:latest rath3t/ikarus:${{ github.ref_name }}
          docker push rath3t/ikarus:${{ github.ref_name }}
          docker save rath3t/ikarus-dev:${{ github.ref_name }} > ikarus-dev-docker-${{ github.ref_name }}.tar
          docker save rath3t/ikarus:${{ github.ref_name }}     > ikarus-docker-${{ github.ref_name }}.tar
          gzip -c9 ikarus-dev-docker-${{ github.ref_name }}.tar > ikarus-dev-docker-${{ github.ref_name }}.tar.gz
          gzip -c9 ikarus-docker-${{ github.ref_name }}.tar > ikarus-docker-${{ github.ref_name }}.tar.gz
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-dev-docker-${{ github.ref_name }}.tar.gz -F 'jsonData={"description":"The docker container to develop with Ikarus",     "categories":["Docker image"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-docker-${{ github.ref_name }}.tar.gz     -F 'jsonData={"description":"The docker container to run examples with Ikarus","categories":["Docker image"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
#          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-dev-docker-${{ github.ref_name }}.zip    -F 'jsonData={"description":"The docker container to develop with Ikarus",     "categories":["Docker image"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
#          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-docker-${{ github.ref_name }}.zip        -F 'jsonData={"description":"The docker container to run examples with Ikarus","categories":["Docker image"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"

      - name: Zip and upload current Ikarus to DARUS
        run: |
          mv repo ikarus-${{ github.ref_name }}
          tar -czf ikarus-${{ github.ref_name }}.tar.gz ./ikarus-${{ github.ref_name }}
          zip -9r  ikarus-${{ github.ref_name }}.zip    ./ikarus-${{ github.ref_name }}
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-${{ github.ref_name }}.tar.gz -F 'jsonData={"description":"Ikarus sources","categories":["Code"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-${{ github.ref_name }}.zip -F 'jsonData={"description":"Ikarus sources","categories":["Code"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"

      - name: Checkout ikarus-examples and create tag, push it, zip it and add it to DARUS
        run: |
          git clone https://github.com/ikarus-project/ikarus-examples.git
          cd ikarus-examples
          git tag ${{ github.ref_name }}
          git push https://${{ secrets.ORGANIZATION_TOKEN }}@github.com/ikarus-project/ikarus-examples.git ${{ github.ref_name }}
          cd ..
          mv ikarus-examples ikarus-examples-${{ github.ref_name }}
          tar -czf ikarus-examples-${{ github.ref_name }}.tar.gz ./ikarus-examples-${{ github.ref_name }}
          zip -9r  ikarus-examples-${{ github.ref_name }}.zip    ./ikarus-examples-${{ github.ref_name }}
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-examples-${{ github.ref_name }}.tar.gz -F 'jsonData={"description":"Ikarus examples","categories":["Code"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"
          curl -H X-Dataverse-key:${{ secrets.DARUS_TOKEN }} -X POST -F file=@ikarus-examples-${{ github.ref_name }}.zip -F 'jsonData={"description":"Ikarus examples","categories":["Code"], "restrict":"false", "tabIngest":"false"}' "https://darus.uni-stuttgart.de/api/datasets/:persistentId/add?persistentId=doi:10.18419/darus-3303"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ORGANIZATION_TOKEN }}"
          automatic_release_tag: ${{ github.ref_name }}
          draft: false
          prerelease: true
          title: ${{ github.ref_name }}
          files: |
            ./ikarus-${{ github.ref_name }}/docs/docs-${{ github.ref_name }}.tar.gz
            ./ikarus-${{ github.ref_name }}/docs/docs-${{ github.ref_name }}.zip
            ikarus-dev-docker-${{ github.ref_name }}.tar.gz
            ikarus-docker-${{ github.ref_name }}.tar.gz
            ikarus-examples-${{ github.ref_name }}.tar.gz
            ikarus-examples-${{ github.ref_name }}.zip
#            ikarus-dev-docker-${{ github.ref_name }}.zip
#            ikarus-docker-${{ github.ref_name }}.zip


