# SPDX-FileCopyrightText: 2022 The Ikarus Developers mueller@ibb.uni-stuttgart.de
# SPDX-License-Identifier: CC0-1.0

name: Docs

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Mkdocs
        run: |
          pip install mkdocs
          pip install git+https://${{ secrets.MKDOCS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mkdocs-macros-plugin
          pip install mkdocs-drawio-exporter
          pip install mkdocs-bibtex
          wget https://github.com/jgraph/drawio-desktop/releases/download/v16.5.1/drawio-amd64-16.5.1.deb
          sudo apt-get install libayatana-appindicator3-1 libnotify4
          sudo dpkg -i drawio-amd64-16.5.1.deb
          sudo apt-get -y -f install
          sudo apt install libasound2 xvfb
      - name: Build Website
        run: |
          cd docs
          cmake -B .build
          cmake --build .build --target site
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ORGANIZATION_TOKEN }}
          external_repository: ikarus-project/ikarus-project.github.io
          publish_dir: ./docs/site
          publish_branch: master
          commit_message: ${{ github.event.head_commit.message }}
