# SPDX-FileCopyrightText: 2022 The Ikarus Developers mueller@ibb.uni-stuttgart.de
# SPDX-License-Identifier: CC0-1.0

name: Docs

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup Mkdocs
        run: |
          pip install mkdocs
          pip install git+https://${{ secrets.MKDOCS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mkdocs-macros-plugin
          pip install mkdocs-drawio-exporter
          pip install mkdocs-glightbox
          pip install mkdocs-bibtex
          pip install mike
          pip install pillow cairosvg
          sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          #wget https://github.com/jgraph/drawio-desktop/releases/download/v16.5.1/drawio-amd64-16.5.1.deb
          #sudo apt-get install libayatana-appindicator3-1 libnotify4
          #sudo dpkg -i drawio-amd64-16.5.1.deb
          #sudo apt-get -y -f install
          #sudo apt install libasound2 xvfb
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Build Website
        run: |
          cd docs
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          mike deploy dev  --config-file mkdocs.insiders.yml --branch main
          mike set-default dev --config-file mkdocs.insiders.yml --branch main

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ORGANIZATION_TOKEN }}
          external_repository: ikarus-project/ikarus-project.github.io
          publish_dir: ./docs/site
          publish_branch: main
          commit_message: ${{ github.event.head_commit.message }}
