name: Ubuntu-GCC-Sanitizers
on: [push]
jobs:
  Ubuntu-GCC-Sanitizers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         path: 'repo'
      - name: Build 
       # working-directory: repo
        run: |
          cd repo
          mkdir cmake-build-debug
          cd cmake-build-debug
          cmake ../  -DUSE_STATIC_ANALYZER="iwyu;cppcheck" -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DUSE_SANITIZER="Address;Memory;MemoryWithOrigins;Undefined;Thread;Leak;Address;Undefined"
          cmake --build . --parallel 9 --target IkarusTests
      - name: Tests
        working-directory: ./repo/cmake-build-debug
        run: ctest --output-on-failure --parallel 4 -C Debug