name: Ubuntu-GCC-Release
on: [push]
jobs:
  Ubuntu-GCC-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         path: 'repo'
      - name: Create Work Dir
        run: mkdir build
      - name: Install dependencies using apt install
        run: |
          sudo apt install gnuplot -y
          sudo apt install liblapack-dev -y 
          sudo apt install libblas-dev -y 
          sudo apt install libsuitesparse-dev -y
          sudo apt install libdune-common-dev -y
          sudo apt install libdune-geometry-dev -y
          sudo apt install libdune-grid-dev -y
          sudo apt install libspdlog-dev -y
          sudo apt install libbenchmark-dev -y
          sudo apt install libgtest-dev -y
      - name: Install dependencies using brew
        run: |
          sudo brew install eigen   
          sudo brew install pybind11
      - name: Build 
       # working-directory: repo 
        run: |
          cd repo
          mkdir cmake-build-release
          cd cmake-build-release
          cmake ../all  -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_C_COMPILER="D:/a/Ikarus/Ikarus/build/winlibs/mingw64/bin/gcc.exe" -DCMAKE_CXX_COMPILER="D:/a/Ikarus/Ikarus/build/winlibs/mingw64/bin/g++.exe"
          cmake --build . --parallel 9
      - name: Tests
        working-directory: ./repo/cmake-build-release
        run: ctest --output-on-failure --parallel 4 -C Release
