name: Ubuntu
on: [push]
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
#          - { waiting until clang fully supports ranges
#            name: "Ubuntu-clang/latest/Debug",
#            config: Debug,
#            compilerC: clang-12,
#            compilerCxx: clang++-12,
#          }
#          - {
#            name: "Ubuntu-clang/latest/Release",
#            config: Release,
#            compilerC: clang-12,
#            compilerCxx: clang++-12,
#          }
          - {
            name: "Ubuntu-GCC/latest/Debug",
            config: Debug,
            compilerC: gcc-11,
            compilerCxx: g++-11,
          }
          - {
            name: "Ubuntu-GCC/latest/Release",
            config: Release,
            compilerC: gcc-11,
            compilerCxx: g++-11,
          }
    steps:
      - uses: actions/checkout@v2
        with:
         path: 'repo'
      - name: Create Work Dir
        run: mkdir -p build
      - name: Install dependencies using apt install
        run: |
          sudo apt-get install -y gnuplot
          sudo apt-get install -y liblapack-dev
          sudo apt-get install -y libblas-dev
          sudo apt-get install -y libsuitesparse-dev
          sudo apt-get install -y libdune-common-dev
          sudo apt-get install -y libdune-geometry-dev
          sudo apt-get install -y libdune-grid-dev
          sudo apt-get install -y libspdlog-dev
          sudo apt-get install -y libbenchmark-dev
          sudo apt-get install -y libgtest-dev
          cd /usr/src/googletest
          sudo cmake .
          sudo cmake --build . --target install
      - name: Cache matplotplusplusAndEigen
        uses: actions/cache@v2
        id: cache-matplotplusplusEigen
        env:
          cache-name: cache-matplotplusplus
        with:
          path: |
            ./matplotplusplus
            ./eigen
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Conditionally download eigen 3.4
        if: "${{ steps.cache-matplotplusplusEigen.outputs.cache-hit != 'true'}}"
        run: git clone https://gitlab.com/libeigen/eigen.git
      - name: Install eigen 3.4
        run: |
          cd eigen
          git checkout 3.4
          mkdir build
          cd build
          cmake ../
          sudo make install
      - name: Install matplotplusplus
        run: |
          mkdir -p matplotplusplus
          cd matplotplusplus
          echo 'cmake_minimum_required(VERSION 3.16)
                project(matplotplusplus)
                include(ExternalProject)
                          ExternalProject_Add(matplotplusplus
                          GIT_REPOSITORY https://github.com/alandefreitas/matplotplusplus.git
                          GIT_TAG master
                          GIT_PROGRESS TRUE
                          CMAKE_ARGS     -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF
                          )' > CMakeLists.txt
          mkdir -p build
          cd build
          cmake ../  -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
          sudo cmake --build . --parallel 9
      - name: Install gcc11
        if: "${{ matrix.config.compilerC == 'gcc-11'}}"
        run: |
          sudo apt install build-essential manpages-dev software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11
      - name: Build 
       # working-directory: repo 
        run: |
          cd repo
          mkdir cmake-build-${{ matrix.config.config }}
          cd cmake-build-${{ matrix.config.config }}
          cmake ../  -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -G "Unix Makefiles" -DCMAKE_C_COMPILER=${{ matrix.config.compilerC }} -DCMAKE_CXX_COMPILER=${{ matrix.config.compilerCxx }} -DCMAKE_CXX_FLAGS="-Wall -Wpedantic -Wextra -Werror"
          cmake --build . --parallel 9 --target IkarusTests
      - name: Tests
        working-directory: ./repo/cmake-build-${{ matrix.config.config }}
        run: ctest --output-on-failure --parallel 4 -C ${{ matrix.config.config }}
