name: Ubuntu-GCC-Release
on: [push]
jobs:
  Ubuntu-GCC-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         path: 'repo'
      - name: Create Work Dir
        run: mkdir build
      - name: Install dependencies using apt install
        run: |
          sudo apt install -y gnuplot 
          sudo apt install -y liblapack-dev  
          sudo apt install -y libblas-dev
          sudo apt install -y libsuitesparse-dev
          sudo apt install -y libdune-common-dev
          sudo apt install -y libdune-geometry-dev
          sudo apt install -y libdune-grid-dev
          sudo apt install -y libspdlog-dev
          sudo apt install -y libbenchmark-dev
          sudo apt install -y libgtest-dev
      - name: Install dependencies using brew
        run: |
          sudo chmod 755 /usr/local/bin
          brew install eigen   
          brew install pybind11
      - name: Build 
       # working-directory: repo 
        run: |
          cd repo
          mkdir cmake-build-release
          cd cmake-build-release
          cmake ../all  -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          cmake --build . --parallel 9
      - name: Tests
        working-directory: ./repo/cmake-build-release
        run: ctest --output-on-failure --parallel 4 -C Release
