name: Ubuntu
on:
  push:
    paths-ignore:
      - 'docs/**'
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container:
      image: rath3t/ci-ubuntu-21-04
    strategy:
      fail-fast: false
      matrix:
        config:
#          - { waiting until clang fully supports ranges
#            name: "Ubuntu-clang/latest/Debug",
#            config: Debug,
#            compilerC: clang-12,
#            compilerCxx: clang++-12,
#          }
#          - {
#            name: "Ubuntu-clang/latest/Release",
#            config: Release,
#            compilerC: clang-12,
#            compilerCxx: clang++-12,
#          }
          - {
            name: "Ubuntu-GCC/latest/Debug",
            config: Debug,
            compilerC: gcc-11,
            compilerCxx: g++-11,
          }
          - {
            name: "Ubuntu-GCC/latest/Release",
            config: Release,
            compilerC: gcc-11,
            compilerCxx: g++-11,
          }
    steps:
      - uses: actions/checkout@v2
        with:
         path: 'repo'
      - name: Build 
        working-directory: ./repo
        run: |
          mkdir cmake-build-${{ matrix.config.config }}
          cd cmake-build-${{ matrix.config.config }}
          cmake ../  -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -G "Unix Makefiles" -DCMAKE_C_COMPILER=${{ matrix.config.compilerC }} -DCMAKE_CXX_COMPILER=${{ matrix.config.compilerCxx }} -DCMAKE_CXX_FLAGS="-Wall -Wpedantic -Wextra -Werror"
          cmake --build . --parallel 9 --target IkarusTests
      - name: Tests
        working-directory: ./repo/cmake-build-${{ matrix.config.config }}
        run: ctest --output-on-failure --parallel 4 -C ${{ matrix.config.config }}
