name: Ubuntu-GCC-Debug-CodeCov
on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  
jobs:
  Ubuntu-GCC-Debug-CodeCov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Work Dir
        run: mkdir build
      - name: Install dependencies using apt install
        run: |
          sudo apt install -y gnuplot 
          sudo apt install -y liblapack-dev  
          sudo apt install -y libblas-dev
          sudo apt install -y libsuitesparse-dev
          sudo apt install -y libdune-common-dev
          sudo apt install -y libdune-geometry-dev
          sudo apt install -y libdune-grid-dev
          sudo apt install -y libspdlog-dev
          sudo apt install -y libbenchmark-dev
          sudo apt install -y libgtest-dev
          cd /usr/src/googletest
          sudo cmake .
          sudo cmake --build . --target install
      - name: Install dependencies using brew
        run: |
          git clone https://gitlab.com/libeigen/eigen.git
          cd eigen
          git checkout 3.4
          ls
          mkdir build
          cd build
          cmake ../
          sudo make install
          ls
          cd ..
          lse
          cd ..
          ls
          rm -r eigen
      - name: Install gcc11
        run: |
          sudo apt install build-essential manpages-dev software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update && sudo apt install gcc-11 g++-11
      - name: Build 
       # working-directory: repo 
        run: |
          mkdir cmake-build-debug
          cd cmake-build-debug
          cmake ../test  -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DENABLE_TEST_COVERAGE=1
          cmake --build . --parallel 9
      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}    
          
      - name: Tests
        working-directory: ./cmake-build-debug
        run: ctest --output-on-failure --parallel 4 -C Debug
      - name: LS
        run: |
           ls
      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
