name: Ubuntu-GCC-Debug-CodeCov
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/ghpages.yml'
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  Ubuntu-GCC-Debug-CodeCov:
    runs-on: ubuntu-latest
    container:
      image: rath3t/ci-ubuntu-21-04
    steps:
      - uses: actions/checkout@v2
      - name: test vars
        run: |
          echo $CI
          echo $GITHUB_ACTIONS
      - name: Create Work Dir
        run: |
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11
      - name: Build
        run: |
          mkdir cmake-build-debug
          cd cmake-build-debug
          cmake ../  -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DENABLE_TEST_COVERAGE=1
          cmake --build . --parallel 9 --target IkarusTests

      - name: Tests
        working-directory: ./cmake-build-debug
        run: ctest --output-on-failure --parallel 4 -C Debug

      - name: collect code coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN} -R ./cmake-build-debug
