name: Windows-MinGW-GCC
on: [push]
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest
    container:
      image: rath3t/ci-windows
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows-Mingw/latest/Release",
            config: Release,
          }
          - {
            name: "Windows-Mingw/latest/Debug",
            config: Debug,
          }
    steps:
    - uses: actions/checkout@v2
      with:
       path: 'repo'

    - name: Build
      run: |
        cd C:
        mkdir cmake-build-${{ matrix.config.config }}
        cd cmake-build-${{ matrix.config.config }}
        cmake ../  -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_C_COMPILER="D:/a/Ikarus/Ikarus/build/winlibs/mingw64/bin/gcc.exe" -DCMAKE_CXX_COMPILER="D:/a/Ikarus/Ikarus/build/winlibs/mingw64/bin/g++.exe"
        cmake --build . --parallel 9 --target Ikarustests
    - name: Tests
      working-directory: ./repo/cmake-build-${{ matrix.config.config }}
      run: ctest --output-on-failure --parallel 4 -C ${{ matrix.config.config }}
