name: Windows
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/ghpages.yml'
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "GCC-Release",
            config: Release,
          }
          - {
            name: "GCC-Debug",
            config: Debug,
          }
    steps:
    - uses: actions/checkout@v2
      with:
       path: 'repo'
#     - name: test docker
#       run: |
#         docker pull rath3t/ci-windows
#
    - name: Cache Winlibs and dependencies
      uses: actions/cache@v2
      id: cache-winlibs-dep
      env:
        cache-name: cache-winlibs-dep
      with:
        path: |
          ./winlibs
          ./Ikarus_Dependencies
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Winlibs
      if: "${{ steps.cache-winlibs-dep.outputs.cache-hit != 'true'}}"
      run: |
        mkdir -p winlibs
        Invoke-WebRequest -Uri https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-12.0.0-9.0.0-r2/winlibs-x86_64-posix-seh-gcc-11.1.0-llvm-12.0.0-mingw-w64-9.0.0-r2.7z -OutFile ./winlibs/libs.7z
        cd winlibs
        7z x libs.7z -bsp1
        rm libs.7z
    - name: Add Winlibs to PATH
      run: |
        echo "D:/a/Ikarus/Ikarus/winlibs/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Download and extract dependencies
      if: "${{ steps.cache-winlibs-dep.outputs.cache-hit != 'true'}}"
      run: |
        mkdir Ikarus_Dependencies
        Invoke-WebRequest -Uri https://github.com/IkarusRepo/IkarusDependencies/releases/download/v0.3/Dependencies_release.7z -OutFile ./Ikarus_Dependencies/dependencies.7z
        cd Ikarus_Dependencies
        7z x dependencies.7z -bsp1
        rm dependencies.7z
    - name: Build
      run: |
        cd repo
        mkdir cmake-build-${{ matrix.config.config }}
        cd cmake-build-${{ matrix.config.config }}
        cmake ../  -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_C_COMPILER="D:/a/Ikarus/Ikarus/winlibs/mingw64/bin/gcc.exe" -DCMAKE_CXX_COMPILER="D:/a/Ikarus/Ikarus/winlibs/mingw64/bin/g++.exe"
        cmake --build . --parallel 9 --target Ikarustests
    - name: Tests
      working-directory: ./repo/cmake-build-${{ matrix.config.config }}
      run: ctest --output-on-failure --parallel 4 -C ${{ matrix.config.config }}
